### ISSUE TITLE
Integration for Venta Ah735

### ISSUE THREAD

**Issue by falkfischer11** [Michsior14/ha-venta#69]
Hello,

is it planned to integrate the model AH730?
If try it to use but without success. (Unknown Error)

Or, is Here a workaround possible?

**Comment by Michsior14** [comment]
Hey!

I don't know anything about this model unfortunately. Could you follow the instructions [here](https://github.com/Michsior14/ha-venta/issues/8#issuecomment-1930920554) to see how this even comunícate?

**Comment by falkfischer11** [comment]
Hi,

i have checked both. But no response. It looks like that the app is different. New App. "Smart Life - Smart Living. In the old app is the device not in. (here the device. it looks like is a new one. https://www.venta-air.com/AH730-AH735-AeroStyle-Compact-Luftbefeuchter/8072 )

**Comment by Michsior14** [comment]
Oh, so they switched to tuya It seems. You can have a try with [this](https://github.com/rospogrigio/localtuya) or official tuya integration.

Beyond that without physical access to the device I cannot really help.

**Comment by helgek** [comment]
I spoke with Venta some months ago and from this conversation I remember that they mentioned the move to Tuya. I asked them to rethink their strategy, at least provide an open interface in parallel since Venta is currently the only quality humidifier device providing a local / cloud free API. 

With tuya it is sometimes possible to reflash the software e.g. with esphome, depending on the microcontroller they use. There are several projects dealing with this, mostly hosted on GitHub. I've done this already with other smarthome devices. For some microcontrollers it is even possible to reflash them without the need to connect to the pcb, but I think with newer models of their microcontrollers it's not possible at the moment to do it purely software based.

**Comment by falkfischer11** [comment]
Hello,

 

thanks for your effort. It looks like that will be worked with local tuya. (switch is working the other values are ongoing)

 

Von: helgek ***@***.***> 
Gesendet: Samstag, 9. November 2024 16:31
An: Michsior14/ha-venta ***@***.***>
Cc: falkfischer11 ***@***.***>; Author ***@***.***>
Betreff: Re: [Michsior14/ha-venta] Integration for Venta Ah735 (Issue #69)

 

I spoke with Venta some months ago and from this conversation I remember that they mentioned the move to Tuya. I asked them to rethink their strategy, at least provide an open interface in parallel since Venta is currently the only quality humidifier device providing a local / cloud free API.

With tuya it is sometimes possible to reflash the software e.g. with esphome, depending on the microcontroller they use. There are several projects dealing with this, mostly hosted on GitHub. I've done this already with other smarthome devices. For some microcontrollers it is even possible to reflash them without the need to connect to the pcb, but I think with newer models of their microcontrollers it's not possible at the moment to do it purely software based.

**Comment by helgek** [comment]
Good to hear. I tried local tuya only ones so far with a galaxy laser projector and the experience wasn't great but it was also a bit of a complicated device. Hopefully it will work well with your device

**Comment by Michsior14** [comment]
Tuya situation mentioned in the readme ;)
